package com.hexincad.entity;
// Generated 2016-11-14 12:02:07 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HxJob generated by hbm2java
 */
@Entity
@Table(name = "hx_job", catalog = "work")
public class HxJob implements java.io.Serializable {

	private String cmd;
	private Long jobId;
	private Set<HxModel> hxModels = new HashSet<HxModel>(0);

	public HxJob() {
	}


	public HxJob(String cmd, Set<HxModel> hxModels) {
		this.cmd = cmd;
		this.hxModels = hxModels;
	}

	@Column(name = "cmd")
	public String getCmd() {
		return cmd;
	}

	public void setCmd(String cmd) {
		this.cmd = cmd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "jobID", unique = true, nullable = false)
	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxJob")
	public Set<HxModel> getHxModels() {
		return this.hxModels;
	}

	public void setHxModels(Set<HxModel> hxModels) {
		this.hxModels = hxModels;
	}

}
