package com.hexincad.entity;
// Generated 2016-11-14 12:02:07 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HxModel generated by hbm2java
 */
@Entity
@Table(name = "hx_model", catalog = "work")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","hxModel","hxJob"})
public class HxModel implements java.io.Serializable {

	private String id;
	private HxModel hxModel;//父节点
	private HxJob hxJob;
	private String modelname;
	private String description;
	private String savepath;
	private Integer modelversion;
	private Date lastmodify;
	private Set<HxModel> hxModels = new HashSet<HxModel>(0);//子节点们
	private Set<HxParam> hxParams = new HashSet<HxParam>(0);

	public HxModel() {
	}

	public HxModel(String id) {
		this.id = id;
	}

	public HxModel(String id, HxModel hxModel, HxJob hxJob, String modelname, String description, String savepath,
			Integer modelversion, Date lastmodify, Set<HxModel> hxModels, Set<HxParam> hxParams) {
		this.id = id;
		this.hxModel = hxModel;
		this.hxJob = hxJob;
		this.modelname = modelname;
		this.description = description;
		this.savepath = savepath;
		this.modelversion = modelversion;
		this.lastmodify = lastmodify;
		this.hxModels = hxModels;
		this.hxParams = hxParams;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 9)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid")
	public HxModel getHxModel() {
		return this.hxModel;
	}

	public void setHxModel(HxModel hxModel) {
		this.hxModel = hxModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobID")
	public HxJob getHxJob() {
		return this.hxJob;
	}

	public void setHxJob(HxJob hxJob) {
		this.hxJob = hxJob;
	}

	@Column(name = "modelname")
	public String getModelname() {
		return this.modelname;
	}

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "savepath")
	public String getSavepath() {
		return this.savepath;
	}

	public void setSavepath(String savepath) {
		this.savepath = savepath;
	}

	@Column(name = "modelversion")
	public Integer getModelversion() {
		return this.modelversion;
	}

	public void setModelversion(Integer modelversion) {
		this.modelversion = modelversion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodify", length = 19)
	public Date getLastmodify() {
		return this.lastmodify;
	}

	public void setLastmodify(Date lastmodify) {
		this.lastmodify = lastmodify;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxModel")
	public Set<HxModel> getHxModels() {
		return this.hxModels;
	}

	public void setHxModels(Set<HxModel> hxModels) {
		this.hxModels = hxModels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxModel")
	public Set<HxParam> getHxParams() {
		return this.hxParams;
	}

	public void setHxParams(Set<HxParam> hxParams) {
		this.hxParams = hxParams;
	}

}
