package com.hexincad.entity;
// Generated 2016-11-14 12:02:07 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * HxParam generated by hbm2java
 */
@Entity
@Table(name = "hx_param", catalog = "work")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","hxModel"})
public class HxParam implements java.io.Serializable {

	private Long id;
	private HxModel hxModel;
	private String paramname;
	private String paramtype;
	private Float paramvalue;
	private Integer paramorder;

	public HxParam() {
	}

	public HxParam(HxModel hxModel, String paramname, String paramtype, Float paramvalue, Integer paramorder) {
		this.hxModel = hxModel;
		this.paramname = paramname;
		this.paramtype = paramtype;
		this.paramvalue = paramvalue;
		this.paramorder = paramorder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelid")
	public HxModel getHxModel() {
		return this.hxModel;
	}

	public void setHxModel(HxModel hxModel) {
		this.hxModel = hxModel;
	}

	@Column(name = "paramname", length = 100)
	public String getParamname() {
		return this.paramname;
	}

	public void setParamname(String paramname) {
		this.paramname = paramname;
	}

	@Column(name = "paramtype", length = 2)
	public String getParamtype() {
		return this.paramtype;
	}

	public void setParamtype(String paramtype) {
		this.paramtype = paramtype;
	}

	@Column(name = "paramvalue", precision = 12, scale = 0)
	public Float getParamvalue() {
		return this.paramvalue;
	}

	public void setParamvalue(Float paramvalue) {
		this.paramvalue = paramvalue;
	}

	@Column(name = "paramorder")
	public Integer getParamorder() {
		return this.paramorder;
	}

	public void setParamorder(Integer paramorder) {
		this.paramorder = paramorder;
	}

}
